# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer1.blocknet.com:
  orderer2.blocknet.com:
  orderer3.blocknet.com:
  # orderer4.blocknet.com:
  # orderer5.blocknet.com:
  peer0.org1.blocknet.com:
  peer1.org1.blocknet.com:
  # peer0.org2.blocknet.com:
  # peer1.org2.blocknet.com:

networks:
  byfn:

services:

  orderer1.blocknet.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer1.blocknet.com
    container_name: orderer1.blocknet.com
    networks:
      - byfn

  orderer2.blocknet.com:
    extends:
      file: base/peer-base.yaml
      service: orderer-base
    container_name: orderer2.blocknet.com
    networks:
    - byfn
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/blocknet.com/orderers/orderer2.blocknet.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/blocknet.com/orderers/orderer2.blocknet.com/tls/:/var/hyperledger/orderer/tls
        - ../store/orderer2.blocknet.com:/var/hyperledger/production/orderer
    ports:
    - 8050:7050

  orderer3.blocknet.com:
    extends:
      file: base/peer-base.yaml
      service: orderer-base
    container_name: orderer3.blocknet.com
    networks:
    - byfn
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/blocknet.com/orderers/orderer3.blocknet.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/blocknet.com/orderers/orderer3.blocknet.com/tls/:/var/hyperledger/orderer/tls
        - ../store/orderer3.blocknet.com:/var/hyperledger/production/orderer
    ports:
    - 9050:7050

  # orderer4.blocknet.com:
  #   extends:
  #     file: base/peer-base.yaml
  #     service: orderer-base
  #   container_name: orderer4.blocknet.com
  #   networks:
  #   - byfn
  #   volumes:
  #       - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
  #       - ../crypto-config/ordererOrganizations/blocknet.com/orderers/orderer4.blocknet.com/msp:/var/hyperledger/orderer/msp
  #       - ../crypto-config/ordererOrganizations/blocknet.com/orderers/orderer4.blocknet.com/tls/:/var/hyperledger/orderer/tls
  #       - ../store/orderer4.blocknet.com:/var/hyperledger/production/orderer
  #   ports:
  #   - 10050:7050

  # orderer5.blocknet.com:
  #   extends:
  #     file: base/peer-base.yaml
  #     service: orderer-base
  #   container_name: orderer5.blocknet.com
  #   networks:
  #   - byfn
  #   volumes:
  #       - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
  #       - ../crypto-config/ordererOrganizations/blocknet.com/orderers/orderer5.blocknet.com/msp:/var/hyperledger/orderer/msp
  #       - ../crypto-config/ordererOrganizations/blocknet.com/orderers/orderer5.blocknet.com/tls/:/var/hyperledger/orderer/tls
  #       - ../store/orderer5.blocknet.com:/var/hyperledger/production/orderer
  #   ports:
  #   - 11050:7050

  peer0.org1.blocknet.com:
    container_name: peer0.org1.blocknet.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org1.blocknet.com
    networks:
      - byfn

  peer1.org1.blocknet.com:
    container_name: peer1.org1.blocknet.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.org1.blocknet.com
    networks:
      - byfn

  # peer0.org2.blocknet.com:
  #   container_name: peer0.org2.blocknet.com
  #   extends:
  #     file:  base/docker-compose-base.yaml
  #     service: peer0.org2.blocknet.com
  #   networks:
  #     - byfn

  # peer1.org2.blocknet.com:
  #   container_name: peer1.org2.blocknet.com
  #   extends:
  #     file:  base/docker-compose-base.yaml
  #     service: peer1.org2.blocknet.com
  #   networks:
  #     - byfn

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:amd64-1.4.4
    tty: true
    stdin_open: true
    environment:
      - SYS_CHANNEL=$SYS_CHANNEL
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.org1.blocknet.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.blocknet.com/peers/peer0.org1.blocknet.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.blocknet.com/peers/peer0.org1.blocknet.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.blocknet.com/peers/peer0.org1.blocknet.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.blocknet.com/users/Admin@org1.blocknet.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ../crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ../scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ../channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer1.blocknet.com
      - orderer2.blocknet.com
      - orderer3.blocknet.com
      # - orderer4.blocknet.com
      # - orderer5.blocknet.com
      - peer0.org1.blocknet.com
      - peer1.org1.blocknet.com
      # - peer0.org2.blocknet.com
      # - peer1.org2.blocknet.com
    networks:
      - byfn
